---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config:
        network:
            - ["forwarded_port", {guest: 50070, host: 50070}]
            - ["forwarded_port", {guest: 50075, host: 50075}]
            - ["forwarded_port", {guest: 50030, host: 50030}]
            - ["forwarded_port", {guest: 50090, host: 50090}]
            - ["forwarded_port", {guest: 4040, host: 4040}]
            - ["forwarded_port", {guest: 16010, host: 16010}]

suites:
  - name: default
    run_list:
      - recipe[bigdata::default]
    attributes:
      java:
        install_flavor: oracle
        jdk_version: 7
        oracle:
          accept_oracle_download_terms: true
